### ISSUE TITLE
mypy type checking

### ISSUE THREAD

**Issue by docent-net** [docent-net/mc-server-manager#7]
Add type checking to backend builds. Helpers:

- https://mypy.readthedocs.io/en/stable/more_types.html
- https://www.blog.pythonlibrary.org/2020/04/15/type-checking-in-python/

**Comment by gilesknap** [comment]
In case you have not come across it. The pyright vscode extension is really good for helping with static type checking and other things too (like auto import - which means you can get auto completion on type hints before you have imported the types). I usually use pyright instead of enabling mypy on large projects.

**Comment by gilesknap** [comment]
Wait, this is about CI! I do use mypi for that ...

**Comment by docent-net** [comment]
Generally this issue is about putting type checking into ci (which is github actions currently - see.github/workflow/..). You can take care of it if you want to :) I'm a beginner in the Python type checking and I know very little about mypy and typing library (especially about more advanced topics when method returns complicated objects).

**Comment by gilesknap** [comment]
FYI, a couple of examples to improve type hinting.

You could do more explicit typing in get_srv_template_files like this:
```
get_srv_template_files(self) -> List[str]:
```

Server instances is currently hinted as returning a Type which is not want you want, if you turn on mypy linting or pyright in vscode it would warn you that ```return srvs``` is not a returning Type of List but a List.

to express what list_server_instances currently returns you would say
```
list_server_instances(self) -> List[Dict[str, Union[str, bool]]]:
```
meaning a list of dictionaries whose index is str and values may be str or bool.

But I would be tempted to create a class for server instance and have a dictionary or list of them. This gives static typing a much more explicit structure to check. Data classes are really good for this sort of structure e.g.
```

from dataclasses import dataclass
@dataclass
class ServerInstance:
    name: str
    secured: bool = False

...
    def list_server_instances(self) -> List[ServerInstance]:
        srvs = []
        pathlist = Path(self.__config.get_servers_data_path()).glob('*')
        for path in pathlist:
            secureFlag = Path(str(path), self.SECURE_SRV_LOCK_NAME).exists()
            srvs.append(ServerInstance(name=str(path.name), secured=secureFlag))
        return srvs
```
